before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - "which ssh-agent || ( apt-get install -qq openssh-client )"
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_development:
  stage: deploy
  environment:
    name: development
  script:
    - >-
      ssh -p $SSH_PORT $SSH_USER@$VM_IPADDRESS "cd ~/dir_name/domain.com && 
      git switch dev && git pull origin dev && 
      cd ~/dir_name/domain.com/deploy && 
      chmod +x development.sh && ./development.sh && 
      chmod -x development.sh"
  only:
    - dev # branch name

deploy_production:
  stage: deploy
  environment:
    name: production
  script:
    - >-
      ssh -p $SSH_PORT $SSH_USER@$VM_IPADDRESS "cd ~/dir_name/domain.com && 
      git switch main && git pull origin main && 
      cd ~/dir_name/domain.com/deploy && 
      chmod +x production.sh && ./production.sh && 
      chmod -x production.sh"
  only:
    - main # branch name